[package]
name = "rustalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.28"
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
serde_json = "1.0.138"
tokio = "1.43.0"
